FROM httpd:2.4.51
# COPY ./dnj_challange_3/apache.conf /usr/local/apache2/conf/dnj_challange_3.apache.conf

# RUN echo "Include /usr/local/apache2/conf/dnj_challange_3.apache.conf" \
#     >> /usr/local/apache2/conf/httpd.conf